// Generated by CoffeeScript 1.5.0
(function() {
  var coffee, proc, query, readline, rl, shell, tid, url;

  url = require('url');

  readline = require('readline');

  coffee = require(__dirname + '/../node_modules/coffee-script');

  tid = null;

  proc = require('child_process');

  shell = proc.spawn('mongo', process.argv.slice(2));

  rl = readline.createInterface(process.stdin, process.stdout);

  query = function() {
    return rl.question('>', function(data) {
      var c;
      try {
        if (data.match(/^(show|use)/)) {
          c = data + "\n";
        } else {
          c = coffee.compile(data.toString(), {
            bare: true
          });
        }
        shell.stdin.write(c);
      } catch (e) {
        shell.stdin.write(data);
      }
      return query();
    });
  };

  shell.stdout.on('data', function(data) {
    process.stdout.write(data.toString());
    if (tid) {
      clearTimeout(tid);
    }
    return tid = setTimeout(query, 100);
  });

  shell.stderr.on('data', function(data) {
    process.stderr.write(data.toString());
    if (tid) {
      clearTimeout(tid);
    }
    return tid = setTimeout(query, 100);
  });

  shell.on('exit', function() {
    return process.exit(0);
  });

}).call(this);
